version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:

    volumes:
      - ./uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend